version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
