{
 "title": "App Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redis Operations/sec",
   "type": "timeseries",
   "description": "Количество команд Redis в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Application Errors (stderr)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"docker\", stream=\"stderr\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество HTTP-запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_count[1m])\r\n"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "description": "95% запросов выполняются быстрее этого времени",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage (Containers)",
   "type": "timeseries",
   "description": "Использование памяти контейнерами",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "CPU Usage (Containers)",
   "type": "timeseries",
   "description": "Процент использования CPU контейнерами",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m]) * 100"
    }
   ]
  }
 ]
}